// ============================================
// Generated by SEA Transpiler
// File: Main.sea
// ============================================

#ifndef MAIN_SEA_a0755b32_H
#define MAIN_SEA_a0755b32_H

int main();

#endif //MAIN_SEA_a0755b32_H
