// ============================================
// Generated by SEA Transpiler
// File: Main.sea
// ============================================

#include "Main.sea.h"
#include "Person.sea.h"

#include <malloc.h>
#include <stdio.h>
#include <time.h>

int main() {
    srand(time(NULL));

    PersonOBJ me = {0};
    Person.initWithName(&me, "Bob");
    PersonOBJ *you = calloc(1, sizeof(PersonOBJ));
    Person.init(you, "Claude", 24);

    char* meStr = Person.toString(&me);
    puts(meStr);
    free(meStr);

    char* youStr = Person.toString(you);
    puts(youStr);
    free(youStr);

    if (Person.equals(&me, you)) {
        puts("They are equal!");
    } else {
        puts("They are not equal!");
    }

    printf("My ID is: %zu\n", Person.getId(&me));
    printf("Your ID is: %zu\n", Person.getId(you));

    free(you);
    return 0;
}