// ============================================
// Generated by SEA Transpiler
// File: Main.sea
// ============================================

#include "Main.sea.h"
#include "Person.sea.h"

#include <malloc.h>
#include <stdio.h>
#include <time.h>

int main() {
    srand(time(NULL));

    Person_OBJ me = {0};
    Person_CLS.INIT_char_ptr(&me, "Bob");
    Person_OBJ *you = calloc(1, sizeof(Person_OBJ));
    Person_CLS.INIT(you, "Claude", 24);

    char* meStr = Person_CLS.FN_toString(&me);
    puts(meStr);
    free(meStr);

    char* youStr = Person_CLS.FN_toString(you);
    puts(youStr);
    free(youStr);

    if (Person_CLS.FN_equals(&me, you)) {
        puts("They are equal!");
    } else {
        puts("They are not equal!");
    }

    printf("My ID is: %zu\n", Person_CLS.FN_getId(&me));
    printf("Your ID is: %zu\n", Person_CLS.FN_getId(you));

    free(you);
    return 0;
}