// ============================================
// Generated by SEA Transpiler
// File: Person.sea
// ============================================

#include "Person.sea.h"
#include "Random.sea.h"

#include <stdio.h>
#include <string.h>
#include <malloc.h>

void Person_INIT(Person_OBJ *self, char *name, int age) {
    self->name = name;
    self->age = age;
    self->id = Person_CLS.STATICFN_generateU64();
}

void Person_INIT_char_ptr(Person_OBJ *self, char *name) {
    self->name = name;
    self->age = 18;
    self->id = Person_CLS.STATICFN_generateU64();
}

char *Person_FN_toString(Person_OBJ *self) {
    size_t size = snprintf(NULL, 0, "Person(name: %s, age: %d, id: %llu)", self->name, self->age, self->id) + 1;
    char *buffer = malloc(size * sizeof(char));
    snprintf(buffer, size, "Person(name: %s, age: %d, id: %llu)", self->name, self->age, self->id);
    return buffer;
}

bool Person_FN_equals(Person_OBJ *self, Person_OBJ *other) {
    return self->id == other->id;
}

size_t Person_FN_getId(Person_OBJ *self) {
    return self->id;
}

size_t Person_STATICFN_generateU64() {
    return Random_CLS.STATICFN_generateU64();
}

const struct Person_CLS Person_CLS = {
        .INIT = Person_INIT,
        .INIT_char_ptr = Person_INIT_char_ptr,
        .FN_toString = Person_FN_toString,
        .FN_equals = Person_FN_equals,
        .FN_getId = Person_FN_getId,
        .STATICFN_generateU64 = Person_STATICFN_generateU64
};