// ============================================
// Generated by SEA Transpiler
// File: Person.sea
// ============================================

#ifndef PERSON_SEA_3c01bdbb_H
#define PERSON_SEA_3c01bdbb_H

#include <stdint.h>
#include <stdbool.h>

typedef struct com_a_b_Person_OBJ{
    char* name;
    int age;
    /*PRIVATE*/ uint64_t id;
} Person_OBJ;

extern const struct Person_CLS {
    /*PRIMARY*/ void (*INIT)(Person_OBJ* self, char* name, int age);
    void (*INIT_char_ptr)(Person_OBJ* self, char* name);
    char* (*FN_toString) (Person_OBJ* self);
    bool (*FN_equals) (Person_OBJ* self, Person_OBJ* other);
    size_t (*FN_getId) (Person_OBJ* self);
    /*STATIC*/ size_t (*STATICFN_generateU64)();
} Person_CLS;

#endif //PERSON_SEA_3c01bdbb_H