// ============================================
// Generated by SEA Transpiler
// File: Person.sea
// ============================================

#ifndef PERSON_SEA_3c01bdbb_H
#define PERSON_SEA_3c01bdbb_H

#include <stdint.h>
#include <stdbool.h>

typedef struct Person {
    char* name;
    int age;
    /*PRIVATE*/ uint64_t p_id;
} Person_OBJ;

extern const struct Person_CLS {
    /*PRIMARY*/ void (*constructor)(Person_OBJ* self, char* name, int age);
    void (*constructor_withName)(Person_OBJ* self, char* name);
    char* (*fn_toString) (Person_OBJ* self);
    bool (*fn_equals) (Person_OBJ* self, Person_OBJ* other);
    size_t (*fn_getId) (Person_OBJ* self);
    /*STATIC*/ size_t (*sfn_generateU64)();
} Person;

#endif //PERSON_SEA_3c01bdbb_H