// ============================================
// Generated by SEA Transpiler
// File: Person.sea
// ============================================

#ifndef PERSON_SEA_3c01bdbb_H
#define PERSON_SEA_3c01bdbb_H

#include <stdint.h>
#include <stdbool.h>

typedef struct Person {
    char* name;
    int age;
    /*PRIVATE*/ uint64_t id;
} PersonOBJ;

extern const struct PersonCLS {
    /*PRIMARY*/ void (*init)(PersonOBJ* self, char* name, int age);
    void (*initWithName)(PersonOBJ* self, char* name);
    char* (*toString) (PersonOBJ* self);
    bool (*equals) (PersonOBJ* self, PersonOBJ* other);
    size_t (*getId) (PersonOBJ* self);
    /*STATIC*/ size_t (*generateU64)();
} Person;

#endif //PERSON_SEA_3c01bdbb_H