// ============================================
// Generated by SEA Transpiler
// File: Person.sea
// ============================================

#include "Person.sea.h"
#include "Random.sea.h"

#include <stdio.h>
#include <string.h>
#include <malloc.h>

typedef char* hchar_ptr;

void Person_init(PersonOBJ *self, char *name, int age) {
    self->name = name;
    self->age = age;
    self->id = Person.generateU64();
}

void Person_initWithName(PersonOBJ *self, char *name) {
    self->name = name;
    self->age = 18;
    self->id = Person.generateU64();
}

hchar_ptr Person_toString(PersonOBJ *self) {
    size_t size = snprintf(NULL, 0, "Person(name: %s, age: %d, id: %llu)", self->name, self->age, self->id) + 1;
    char *buffer = malloc(size * sizeof(char));
    snprintf(buffer, size, "Person(name: %s, age: %d, id: %llu)", self->name, self->age, self->id);
    return buffer;
}

bool Person_equals(PersonOBJ *self, PersonOBJ *other) {
    return self->id == other->id;
}

size_t Person_getId(PersonOBJ *self) {
    return self->id;
}

size_t Person_generateU64() {
    return Random.generateU64();
}

const struct PersonCLS Person = {
    .init = Person_init,
    .initWithName = Person_initWithName,
    .toString = Person_toString,
    .equals = Person_equals,
    .getId = Person_getId,
    .generateU64 = Person_generateU64
};