// ============================================
// Generated by SEA Transpiler
// File: Random.sea
// ============================================

#include "Random.sea.h"

#include <stdlib.h>

uint64_t Random_generateU64() {
    return (uint64_t)rand();
}

const struct Random_CLS Random = {
    .generateU64 = Random_generateU64
};