// ============================================
// Generated by SEA Transpiler
// File: Random.sea
// ============================================

#ifndef RANDOM_SEA_cfb07073_H
#define RANDOM_SEA_cfb07073_H

#include <stdint.h>

extern const struct Random_CLS {
    uint64_t (*STATICFN_generateU64)();
} Random_CLS;

#endif //RANDOM_SEA_cfb07073_H