// ============================================
// Generated by SEA Transpiler
// File: Random.sea
// ============================================

#include "Random.sea.h"

#include <stdlib.h>

uint64_t Random_STATICFN_generateU64() {
    return (uint64_t)rand();
}

const struct Random_CLS Random_CLS = {
    .STATICFN_generateU64 = Random_STATICFN_generateU64
};