// ============================================
// Generated by SEA Transpiler
// File: Random.sea
// ============================================

#include "Random.h"

#include <time.h>
#include <stdio.h>

static uint64_t state = 0;

static uint64_t randUint64() {
    if (state == 0) {
        state = (uint64_t) time(NULL) | 1;
    }
    uint64_t x = state;
    x ^= x >> 12;
    x ^= x << 25;
    x ^= x >> 27;
    state = x;
    return x * UINT64_C(2685821657736338717);
}

const struct Random_CLS Random = {
        .randUint64 = randUint64,
};