#ifndef SEA_JSON_TYPE_H
#define SEA_JSON_TYPE_H

#include "Config/CompConfig.h"

typedef enum {
	SEA_JSON_NULL,
	SEA_JSON_BOOL,
	SEA_JSON_NUMBER,
	SEA_JSON_STRING,
	SEA_JSON_ARRAY,
	SEA_JSON_OBJECT
} SEA_JSONType;

#if SEA_CONFIG_ENABLE_PREFIXLESS == 1
typedef SEA_JSONType JSONType;
#endif

#endif //SEA_JSON_TYPE_H
